CREATE TABLE public.tb_address (
    id bigint NOT NULL,
    complement character varying(255),
    district character varying(255),
    number integer,
    zip_code character varying(255),
    city_id bigint,
    client_id bigint
);


--
-- Name: tb_address_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_cart; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_cart (
    id bigint NOT NULL,
    client_id bigint
);


--
-- Name: tb_cart_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_checkout; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_checkout (
    order_status integer,
    cart_id bigint NOT NULL
);


--
-- Name: tb_city; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_city (
    id bigint NOT NULL,
    name character varying(255),
    state_id bigint
);


--
-- Name: tb_city_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_city ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_city_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_client; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_client (
    id bigint NOT NULL,
    cpf character varying(255),
    email character varying(255),
    name character varying(255),
    password character varying(255),
    phone character varying(255)
);


--
-- Name: tb_client_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_order_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_order_item (
    price double precision,
    quantity integer,
    product_id bigint NOT NULL,
    cart_id bigint NOT NULL
);


--
-- Name: tb_product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_product (
    id bigint NOT NULL,
    image character varying(255),
    name character varying(255),
    price double precision,
    score integer
);


--
-- Name: tb_product_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_state (
    id bigint NOT NULL,
    name character varying(255)
);


--
-- Name: tb_state_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_state ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_state_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_address tb_address_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_address
    ADD CONSTRAINT tb_address_pkey PRIMARY KEY (id);


--
-- Name: tb_cart tb_cart_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_cart
    ADD CONSTRAINT tb_cart_pkey PRIMARY KEY (id);


--
-- Name: tb_checkout tb_checkout_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_checkout
    ADD CONSTRAINT tb_checkout_pkey PRIMARY KEY (cart_id);


--
-- Name: tb_city tb_city_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_city
    ADD CONSTRAINT tb_city_pkey PRIMARY KEY (id);


--
-- Name: tb_client tb_client_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_client
    ADD CONSTRAINT tb_client_pkey PRIMARY KEY (id);


--
-- Name: tb_order_item tb_order_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_order_item
    ADD CONSTRAINT tb_order_item_pkey PRIMARY KEY (cart_id, product_id);


--
-- Name: tb_product tb_product_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_product
    ADD CONSTRAINT tb_product_pkey PRIMARY KEY (id);


--
-- Name: tb_state tb_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_state
    ADD CONSTRAINT tb_state_pkey PRIMARY KEY (id);


--
-- Name: tb_city fk1rn7oty4mwqviyw8vk67crapo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_city
    ADD CONSTRAINT fk1rn7oty4mwqviyw8vk67crapo FOREIGN KEY (state_id) REFERENCES public.tb_state(id);


--
-- Name: tb_order_item fk4h5xid5qehset7qwe5l9c997x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_order_item
    ADD CONSTRAINT fk4h5xid5qehset7qwe5l9c997x FOREIGN KEY (product_id) REFERENCES public.tb_product(id);


--
-- Name: tb_order_item fk5u2xbtd9qb6a6spbwf5ajjqxx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_order_item
    ADD CONSTRAINT fk5u2xbtd9qb6a6spbwf5ajjqxx FOREIGN KEY (cart_id) REFERENCES public.tb_cart(id);


--
-- Name: tb_cart fkholodikofugvvvc77ychxl2in; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_cart
    ADD CONSTRAINT fkholodikofugvvvc77ychxl2in FOREIGN KEY (client_id) REFERENCES public.tb_client(id);


--
-- Name: tb_address fkmgkeodciwq4rofwws5m08v1yh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_address
    ADD CONSTRAINT fkmgkeodciwq4rofwws5m08v1yh FOREIGN KEY (client_id) REFERENCES public.tb_client(id);


--
-- Name: tb_address fkpm4x3qy2wea2p4ea7bs217nr5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_address
    ADD CONSTRAINT fkpm4x3qy2wea2p4ea7bs217nr5 FOREIGN KEY (city_id) REFERENCES public.tb_city(id);


--
-- Name: tb_checkout fkpsydhnnl6eqts2wu1fbkjwjpc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_checkout
    ADD CONSTRAINT fkpsydhnnl6eqts2wu1fbkjwjpc FOREIGN KEY (cart_id) REFERENCES public.tb_cart(id);


--
-- PostgreSQL database dump complete
--

